version: "3.9"
services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    image: trading-kit-scanner
    environment:
      - SCAN_INTERVAL=60
      - EXCHANGE=binance
      - SYMBOLS=BTC/USDT,ETH/USDT,SOL/USDT,BNB/USDT,XRP/USDT
      - TIMEFRAMES=1m,5m,15m,1h,4h,1d
    volumes:
      - marketdb:/app
    working_dir: /app/scanner
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: trading-kit-ui
    ports:
      - "4000:4000"
    environment:
      - DB_PATH=/data/market_data.sqlite
    volumes:
      - marketdb:/data
    depends_on:
      - scanner

volumes:
  marketdb:
